doc

diff --git a/check-push b/check-push
--- a/check-push
+++ b/check-push
@@ -7,5 +7,11 @@ then
 fi
 git add .
 git commit -v
+if [ $? -eq 1 ]
+then
+    # most likely empty message
+    echo "Exiting, commit failed"
+    exit 1
+fi
 git push
 git push --tags
